### ISSUE TITLE
Address field is blank

### ISSUE THREAD

**Issue by LoveMyData** [planningalerts-scrapers/wagga#1]
No sure is it the right place to report scraper not working properly.

This scraper is current saving address with a single white space.

**Comment by henare** [comment]
> No sure is it the right place to report scraper not working properly.

Sure is :+1: 

> This scraper is current saving address with a single white space.

That's definitely no good. I've stopped it from auto-running so it doesn't keep getting bad data.

**Comment by LoveMyData** [comment]
I will update the code, found this link and this is all we need, this council is now using iFrame, I may have a crack with Ruby..

https://eservices.wagga.nsw.gov.au/T1PRWeb/eProperty/P1/WWCustom/eTrack/daexhibitionlist.asp

**Comment by LoveMyData** [comment]
fixed with commit b76f4e64b6d41758ead9f0e3803fce86fc6f082e
